### ISSUE TITLE
Change the way the new clipboard works

### ISSUE THREAD

**Issue by kirbyfan64** [nilnor/howl#30]
The new clipboard is great. However, it can be frustrating because nothing copied leaves Howl's clipboard. Therefore, if I want to paste something anywhere else, I have to use GEdit. My idea is to edit Howl's clipboard AND the system clipboard. If that won't work, another idea is a ctrl+shift+c command that modifies both clipboards.

Also, could editor-paste be modified to paste from the system clipboard if Howl's is empty? Again, not being able to paste from external sources can be really frustrating at times.

**Comment by kirbyfan64** [comment]
aaaaaaand...IT'S BACK!!!! Turns out, it happens when I do this:

- Open 2 Howl windows.
- Copy some text from the second one.
- Close both.
- Reopen the first one.
- The clipboard's empty!

**Comment by kirbyfan64** [comment]
Actually, it seems like *anything* I copy with the two windows open gets destroyed...

**Comment by nilnor** [comment]
Thanks for the additional information, I could reproduce it now. I added a fix for this that seems to take care of it for me, let me know if it works for you.

**Comment by nilnor** [comment]
@kirbyfan64 Any update?

**Comment by kirbyfan64** [comment]
@nilnor Sorry. It works now! Thanks!
