### ISSUE TITLE
Don't always strip whitespace

### ISSUE THREAD

**Issue by kirbyfan64** [nilnor/howl#42]
Would an option to save without stripping whitespace be possible? Right now (literally, like 2 minutes ago), I had to redo a [PR for pconfigure](https://github.com/palmer-dabbelt/pconfigure/pull/8) because Howl stripped whitespace.

I personally don't mind, but this isn't the first project where I've had to open gedit to add back spaces for my PR to get merged...

**Comment by shalabhc** [comment]
A config variable for this already exists. Try this in your init.moon:

howl.config.strip_trailing_whitespace = false

**Comment by kirbyfan64** [comment]
But, is there a way to do it on a per-file basis? Not for everything?

**Comment by shalabhc** [comment]
You could open the file and run this command: set-for-buffer strip_trailing_whitespace=false

Also, if you want to configure this for a directory, see the example here which sets config.indent for all files under a specific directory:
http://howl.io/doc/manual/configuration.html#setting-variables-upon-startup

**Comment by nilnor** [comment]
As @shalabhc wrote this is already supported, either for a particular already open file using the `set-for-buffer` command, or by programmatically changing the buffer config as per the linked docs.

I think it could be useful in the future to support project-settings, e.g. by automatically loading a particular file in the project root if it exists, but it's not something I'll be working on right now.

**Comment by kirbyfan64** [comment]
Didn't realize there was a set-for-buffer command. That'll work. Thanks!
