### ISSUE TITLE
Lots of Gtk-Critical warnings when closing with open readline

### ISSUE THREAD

**Issue by kirbyfan64** [nilnor/howl#43]
Whenever do the following:

- open file from command line (`howl myfile`)
- search for nonexistent string (Control-F, then type something random)
- press the close button on the window

I get this:

```
(howl:26496): Gtk-CRITICAL **: gtk_widget_get_parent: assertion 'GTK_IS_WIDGET (widget)' failed

(howl:26496): GLib-GObject-CRITICAL **: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(howl:26496): GLib-GObject-CRITICAL **: g_object_freeze_notify: assertion 'G_IS_OBJECT (object)' failed

(howl:26496): Gtk-CRITICAL **: gtk_widget_has_default: assertion 'GTK_IS_WIDGET (widget)' failed

(howl:26496): Gtk-CRITICAL **: gtk_widget_get_receives_default: assertion 'GTK_IS_WIDGET (widget)' failed

(howl:26496): GLib-GObject-CRITICAL **: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(howl:26496): Gtk-CRITICAL **: gtk_widget_get_display: assertion 'GTK_IS_WIDGET (widget)' failed

(howl:26496): Gdk-CRITICAL **: gdk_display_get_device_manager: assertion 'GDK_IS_DISPLAY (display)' failed

(howl:26496): Gdk-CRITICAL **: gdk_device_manager_list_devices: assertion 'GDK_IS_DEVICE_MANAGER (device_manager)' failed

(howl:26496): Gdk-CRITICAL **: gdk_device_manager_list_devices: assertion 'GDK_IS_DEVICE_MANAGER (device_manager)' failed

(howl:26496): Gdk-CRITICAL **: gdk_device_manager_list_devices: assertion 'GDK_IS_DEVICE_MANAGER (device_manager)' failed

(howl:26496): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(howl:26496): GLib-GObject-CRITICAL **: g_object_notify: assertion 'G_IS_OBJECT (object)' failed

(howl:26496): Gtk-CRITICAL **: gtk_widget_has_default: assertion 'GTK_IS_WIDGET (widget)' failed

(howl:26496): GLib-GObject-CRITICAL **: g_object_thaw_notify: assertion 'G_IS_OBJECT (object)' failed

(howl:26496): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
```

If I re-open the file and do the same things again, no warnings appear. It's pretty weird.

**Comment by nilnor** [comment]
I can't reproduce this. What distro/version/etc are you using? Also, you didn't happen to be in the middle of a system update? When I've seen these things that's typically the reason.

**Comment by kirbyfan64** [comment]
No. In fact, I haven't updated my system in over a month.

Here's what `uname -a` prints:

```
Linux DevPC-LX 3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:22:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

I bit of toying with signal handlers/backtraces shows that these are actually occuring during the call to `lua_close`. That's all I've found so far. Setting Gtk+ to abort on warning and using a custom signal handler in order to get a Lua stack trace just showed that it was some C function, probably in Gtk+'s Lua bindings.

**Comment by nilnor** [comment]
Howl uses direct FFI bindings for Gtk, so it's not in a binding library. I'm guessing it's to do with garbage collection, i.e. resources/references being released upon close, while Gtk is already in a shut-down stage. I just managed to reproduce it, so I'll try to have a look at it later. It's seems to be triggering with an open readline, so I've updated title to reflect this.

**Comment by nilnor** [comment]
So, I believe I've fixed it (couldn't reproduce any more at any rate despite many attempts), but if you could confirm that it doesn't happen for you any more that would be great.

**Comment by kirbyfan64** [comment]
Looks like it's fixed. Thanks!
