### ISSUE TITLE
Confusion with auto indents

### ISSUE THREAD

**Issue by kirbyfan64** [nilnor/howl#50]
Ok...I'm sure there's a simple answer, and this might not be a bug...

BUT I HAVE NO CLUE WHAT'S WRONG!!!!

I'm trying to write my own lexer. I have this for my mode:

```moonscript
{
  lexer: bundle_load 'felix/lexer'

  comment_syntax: { '/*', '*/' }

  auto_pairs: {
    '(': ')'
    '[': ']'
    '{': '}'
    '"': '"'
    "'": "'"
    '"""': '"""'
    "'''": "'''"
  },

  indentation: {
    more_after: '^%s*({|do)%s*$'
    less_for: '^%s+(}|done)%s*$'
  }
}
```

The problem is that the opening curly brace (`{`) doesn't open a new indent. The `do` keyword works. I don't know why.

Please help me!

**Comment by shalabhc** [comment]
I believe Lua patterns don't support alternation with ``|`` - they're not regular expressions. To use regexes, prefix the string with 'r' (e.g. ``r'a|b'``) and fix the syntax (i.e use ``'\\s'``, not ``'%s'``). 

Alternatively, try rewriting as two distinct patterns in a table:
```lua
    more_after: {
     '%s*{%s*$',
     '%s*do%s*$'
    }
```
Btw, why require only whitespace on the line *before* '{' - is that a language requirement?

Also, I noticed you have multi-character ``auto_pairs`` - I didn't think this worked - did it work for you?

Cheers,
Shalabh

**Comment by kirbyfan64** [comment]
@shalabhc

> I believe Lua patterns don't support alternation with | - they're not regular expressions. To use regexes, prefix the string with 'r' (e.g. r'a|b') and fix the syntax (i.e use '\\s', not '%s').

Gah, I forgot that patterns don't support that. Argh.

> Btw, why require only whitespace on the line before '{' - is that a language requirement?

No. That's what happens when you write lexers when you're tired.

This still doesn't work, though:

```moonscript
  indentation: {
    more_after: r'({|do)\\s*$'
    less_for: r'^\\s+(}|done)\\s*$'
  }
```

Now *nothing* indents correctly.

> Also, I noticed you have multi-character auto_pairs - I didn't think this worked - did it work for you?

I'm not even sure what that does with quoted strings. I just put it because...well, because.

Now I'm still trying to figure out what the heck `code_blocks` does...

**Comment by nilnor** [comment]
`more_after` and `less_for` can only be tables, so move the two patterns into tables. As an aside you probably want to edit the `more_after` pattern slightly to avoid lines such as `var = sudo` matching, either requiring a space or some other boundary matching `do`.

`code_blocks`, available only as multi-line blocks for now, is for automatically filling in the corresponding block end marker if necessary when pressing `enter`, along with correctly indenting the middle line. Each block spec consists of a block-start pattern, a block-end matching pattern and the actual block end string. You can see the relevant specs [here](http://howl.io/doc/spec/editing/formatting_spec.html). E.g. to automatically add the `done` and position the cursor correctly for your syntax, you'd want something like this (adapted from the Lua bundle):

```moonscript
  code_blocks:
    multiline: {
      { r'(^\\s*|\\s+)do\\s*$', '^%s*done', 'done' },
  }
```

The creation of a bundle, etc., should of course be documented sometime in the future, but so far there has been no time for it yet. Of course, should you feel a desire to document your journey then this could be this magical moment :)

And last, `auto_pairs` is only for single characters.

**Comment by kirbyfan64** [comment]
@nilnor Thank you so much!

> The creation of a bundle, etc., should of course be documented sometime in the future, but so far there has been no time for it yet. Of course, should you feel a desire to document your journey then this could be this magical moment :)

I might. I'm behind on a *lot* of stuff, so, if/when I do it, it'll be a bit.
