### ISSUE TITLE
Ctrl-F to go to next match not working?

### ISSUE THREAD

**Issue by kirbyfan64** [nilnor/howl#53]
I'm not sure what it is. All I know is that, since some recent update, I can't to to the next search match. If I press `Ctrl-F` to search, search something, and press `Ctrl-F` to go to the next occurrence, nothing happens. Same thing for `Ctrl-R` to go to the previous match.

**Comment by shalabhc** [comment]
I've submitted a patch. Could you please try now? Sorry I didn't realize my commit would auto close this issue.
