### ISSUE TITLE
Failed to find/load application icon

### ISSUE THREAD

**Issue by kirbyfan64** [nilnor/howl#69]
I just start up Howl, and this comes up:

```
Failed to find application icon
```

I thought I had just screwed up my system somehow, until @bunster got a similar error:

```
Failed to load application icon: ../lib/ljglibs/gtk/window.moon:96: Couldn't recognise the image file format for file '/Users/boonie/Projects/howl/share/icons/hicolor/scalable/apps/howl.svg' (code: 3)
```

**Comment by nilnor** [comment]
The two above examples are actually separate. in the first one the icon file can't be found. Something to do with your installation and/or how the root dir is found. Would be great if you could add some printouts to `Application._load_application_icon` and have a look at where it attempts to find the file, and then we can figure out what the error is.

The second I presume has something to do with SVG support on OS X, will search around some for that one.

**Comment by kirbyfan64** [comment]
If I put a print in `application.moon` here:

```moonscript
    for dir in *{ @root_dir.parent, @root_dir }
      print "icon: #{dir}"
      icon = dir\join('share/icons/hicolor/scalable/apps/howl.svg')
      if icon.exists
        status, err = pcall Gtk.Window.set_default_icon_from_file, icon.path
        log.error "Failed to load application icon: #{err}" unless status
        return
```

It prints:

```
icon: /usr/local/share
icon: /usr/local/share/howl
```

I'm guessing either:

1. Howl should also search `@root_dir.parent.parent`
2. The line `icon = dir\join('share/icons/hicolor/scalable/apps/howl.svg')` should be changed to `icon = dir\join('icons/hicolor/scalable/apps/howl.svg')`.

**Comment by nilnor** [comment]
I went for a variant of `1`. `2` wouldn't work, since we want to support both running it from a globally installed version and running it directly from the checkout.

**Comment by kirbyfan64** [comment]
@nilnor Thanks!
